# Generated by Django 3.2.13 on 2022-06-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tracker', '0004_auto_20220630_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedexpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('numberofusers', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('expenses', models.ManyToManyField(blank=True, null=True, related_name='expenses', to='tracker.Expense')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='users', to='users.User')),
            ],
            options={
                'verbose_name': 'sharedexpense',
                'verbose_name_plural': 'sharedexpenses',
                'ordering': ['-id'],
            },
        ),
    ]
